services:
  backend:
    build: ./backend
    container_name: boum-backend
    networks:
      - boum-network
    environment:
      - DATABASE_URL=sqlite+pysqlite:///${DATABASE_DEST_DIR}/${DATABASE_FILE}
      - UPLOAD_FOLDER=${VIDEO_DEST_DIR:-/data/upload}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GPUSTACK_API_TOKEN=${GPUSTACK_API_TOKEN}
      - SPEECH_UPSTREAM_URL=${SPEECH_UPSTREAM_URL}
      - COMPLETIONS_UPSTREAM_URL=${COMPLETIONS_UPSTREAM_URL}
      - POINTCLOUD_OUTPUT_BASE_DIR=${POINTCLOUD_OUTPUT_BASE_DEST_DIR:-/data/pointclouds}
      - SPEECH_MODEL=${SPEECH_MODEL}
      - COMPLETIONS_MODEL=${COMPLETIONS_MODEL}
      - POINTCLOUD_RELATIVE_PATH=${POINTCLOUD_RELATIVE_PATH:-Reconstruction_Outputs/point_cloud_cleaned.ply}
    volumes:
      - ${DATABASE_LOCAL_DIR}:${DATABASE_DEST_DIR}:rw
      - ${VIDEO_LOCAL_DIR}:${VIDEO_DEST_DIR}:rw
      - ${POINTCLOUD_OUTPUT_BASE_LOCAL_DIR}:${POINTCLOUD_OUTPUT_BASE_DEST_DIR}:ro

  video_processor:
    build: ./video_processing_worker
    container_name: boum-video-processor
    networks:
      - boum-network
    environment:
      - VIDEO_INPUT_DIR=${VIDEO_DEST_DIR:-/data/upload}
      - DATABASE_URL=sqlite+pysqlite:///${DATABASE_DEST_DIR}/${DATABASE_FILE}

      - SLURM_HOST=${SLURM_HOST}
      - SLURM_USER=${SLURM_USER}
      - SLURM_BATCH_FILE=${SLURM_BATCH_FILE}

      - SSH_KEY_FILE=${SSH_KEY_DEST_FILE}
      - KNOWN_HOSTS_FILE=${KNOWN_HOSTS_DEST_FILE}

      - NUM_WORKERS=${NUM_VIDEO_PROCESSING_WORKERS}
    volumes:
      - ${VIDEO_LOCAL_DIR}:${VIDEO_DEST_DIR}:ro
      - ${DATABASE_LOCAL_DIR}:${DATABASE_DEST_DIR}:rw
      - ${SSH_KEY_LOCAL_FILE}:${SSH_KEY_DEST_FILE}:ro
      - ${KNOWN_HOSTS_LOCAL_FILE}:${KNOWN_HOSTS_DEST_FILE}:ro

  frontend:
    build:
      context: ./frontend
      args:
        - PUBLIC_API_BASE_URL=${PUBLIC_API_BASE_URL:-https://plant3d.ips.unibe.ch/api}
    container_name: boum-frontend
    networks:
      - boum-network
    depends_on:
      - backend
    environment:
      - PUBLIC_API_BASE_URL=${PUBLIC_API_BASE_URL:-https://plant3d.ips.unibe.ch/api}

  caddy:
    image: docker.io/caddy:alpine
    container_name: boum-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/etc/caddy/certs:ro
    networks:
      - boum-network
    depends_on:
      - backend
      - frontend

networks:
  boum-network:
    driver: bridge
